// <auto-generated />
using ElectronicPartsPicker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicPartsPicker.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20230214004651_Products")]
    partial class Products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicPartsPicker.Order", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderNumber"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ElectronicPartsPicker.Products.Memory", b =>
                {
                    b.Property<int>("MemoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("memoryValue")
                        .HasColumnType("float");

                    b.HasKey("MemoryId");

                    b.ToTable("Memorys");
                });

            modelBuilder.Entity("ElectronicPartsPicker.Products.Motherboard", b =>
                {
                    b.Property<int>("MotherboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotherboardId"));

                    b.Property<string>("MotherboardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MotherboardPrice")
                        .HasColumnType("float");

                    b.HasKey("MotherboardId");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("ElectronicPartsPicker.Products.Nic", b =>
                {
                    b.Property<int>("NicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NicId"));

                    b.Property<string>("NicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NicValue")
                        .HasColumnType("float");

                    b.HasKey("NicId");

                    b.ToTable("Nic");
                });

            modelBuilder.Entity("ElectronicPartsPicker.Products.Processor", b =>
                {
                    b.Property<int>("ProcessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessorId"));

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProcessorValue")
                        .HasColumnType("float");

                    b.HasKey("ProcessorId");

                    b.ToTable("Processor");
                });

            modelBuilder.Entity("ElectronicPartsPicker.Products.gpu", b =>
                {
                    b.Property<int>("gpuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gpuId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("gpuValue")
                        .HasColumnType("float");

                    b.HasKey("gpuId");

                    b.ToTable("GPUs");
                });
#pragma warning restore 612, 618
        }
    }
}
